export const handler = async (): Promise<void> => {
  throw new Error('An unexpected error ocurred')
}
